steps:
  # Build the Docker image.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/pmh-scheduling',
      '.'
    ]
  # Push the Docker image to Container Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/pmh-scheduling'
    ]
  # Deploy to Cloud Run.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          gcloud run deploy pmh-scheduling \
            --image gcr.io/$PROJECT_ID/pmh-scheduling \
            --region asia-east2 \
            --platform managed \
            --allow-unauthenticated \
            --service-account 896330601032-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY